spring:
  application:
    name: "Finances API"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_DEFAULT_SCHEMA}
  devtools:
    livereload:
      enabled: true
  flyway:
    enabled: true
    default-schema: ${DB_DEFAULT_SCHEMA}
  data:
    rest:
      default-media-type: application/json
      return-body-on-create: true
      return-body-on-update: true
      base-path: /
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /api-docs
  paths-to-exclude: [/error, /profile/**, /**/search/**]
  show-actuator: false
  
